package com.yan.shop.entity;

import java.sql.Timestamp;
import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.start_name
     *
     * @mbggenerated
     */
    private String startName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbggenerated
     */
    private int type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.search_times
     *
     * @mbggenerated
     */
    private int searchTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.have_brush_single
     *
     * @mbggenerated
     */
    private int haveBrushSingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.evaluation_times
     *
     * @mbggenerated
     */
    private int evaluationTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.have_pictrue_evaluation_times
     *
     * @mbggenerated
     */
    private int havePictrueEvaluationTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sales_count
     *
     * @mbggenerated
     */
    private int salesCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brush_single_times
     *
     * @mbggenerated
     */
    private int brushSingleTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brush_single_cost
     *
     * @mbggenerated
     */
    private double brushSingleCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.details_optimization
     *
     * @mbggenerated
     */
    private int detailsOptimization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.analyze
     *
     * @mbggenerated
     */
    private String analyze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;


    private int haveTogether;

    public int getHaveTogether() {
        return haveTogether;
    }

    public void setHaveTogether(int haveTogether) {
        this.haveTogether = haveTogether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.start_name
     *
     * @return the value of goods.start_name
     *
     * @mbggenerated
     */
    public String getStartName() {
        return startName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.start_name
     *
     * @param startName the value for goods.start_name
     *
     * @mbggenerated
     */
    public void setStartName(String startName) {
        this.startName = startName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbggenerated
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbggenerated
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.search_times
     *
     * @return the value of goods.search_times
     *
     * @mbggenerated
     */
    public int getSearchTimes() {
        return searchTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.search_times
     *
     * @param searchTimes the value for goods.search_times
     *
     * @mbggenerated
     */
    public void setSearchTimes(int searchTimes) {
        this.searchTimes = searchTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.key_word
     *
     * @return the value of goods.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.key_word
     *
     * @param keyWord the value for goods.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.have_brush_single
     *
     * @return the value of goods.have_brush_single
     *
     * @mbggenerated
     */
    public int getHaveBrushSingle() {
        return haveBrushSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.have_brush_single
     *
     * @param haveBrushSingle the value for goods.have_brush_single
     *
     * @mbggenerated
     */
    public void setHaveBrushSingle(int haveBrushSingle) {
        this.haveBrushSingle = haveBrushSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.evaluation_times
     *
     * @return the value of goods.evaluation_times
     *
     * @mbggenerated
     */
    public int getEvaluationTimes() {
        return evaluationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.evaluation_times
     *
     * @param evaluationTimes the value for goods.evaluation_times
     *
     * @mbggenerated
     */
    public void setEvaluationTimes(int evaluationTimes) {
        this.evaluationTimes = evaluationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.have_pictrue_evaluation_times
     *
     * @return the value of goods.have_pictrue_evaluation_times
     *
     * @mbggenerated
     */
    public int getHavePictrueEvaluationTimes() {
        return havePictrueEvaluationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.have_pictrue_evaluation_times
     *
     * @param havePictrueEvaluationTimes the value for goods.have_pictrue_evaluation_times
     *
     * @mbggenerated
     */
    public void setHavePictrueEvaluationTimes(int havePictrueEvaluationTimes) {
        this.havePictrueEvaluationTimes = havePictrueEvaluationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sales_count
     *
     * @return the value of goods.sales_count
     *
     * @mbggenerated
     */
    public int getSalesCount() {
        return salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sales_count
     *
     * @param salesCount the value for goods.sales_count
     *
     * @mbggenerated
     */
    public void setSalesCount(int salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brush_single_times
     *
     * @return the value of goods.brush_single_times
     *
     * @mbggenerated
     */
    public int getBrushSingleTimes() {
        return brushSingleTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brush_single_times
     *
     * @param brushSingleTimes the value for goods.brush_single_times
     *
     * @mbggenerated
     */
    public void setBrushSingleTimes(int brushSingleTimes) {
        this.brushSingleTimes = brushSingleTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brush_single_cost
     *
     * @return the value of goods.brush_single_cost
     *
     * @mbggenerated
     */
    public double getBrushSingleCost() {
        return brushSingleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brush_single_cost
     *
     * @param brushSingleCost the value for goods.brush_single_cost
     *
     * @mbggenerated
     */
    public void setBrushSingleCost(double brushSingleCost) {
        this.brushSingleCost = brushSingleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.details_optimization
     *
     * @return the value of goods.details_optimization
     *
     * @mbggenerated
     */
    public int getDetailsOptimization() {
        return detailsOptimization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.details_optimization
     *
     * @param detailsOptimization the value for goods.details_optimization
     *
     * @mbggenerated
     */
    public void setDetailsOptimization(int detailsOptimization) {
        this.detailsOptimization = detailsOptimization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.analyze
     *
     * @return the value of goods.analyze
     *
     * @mbggenerated
     */
    public String getAnalyze() {
        return analyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.analyze
     *
     * @param analyze the value for goods.analyze
     *
     * @mbggenerated
     */
    public void setAnalyze(String analyze) {
        this.analyze = analyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_by
     *
     * @return the value of goods.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_by
     *
     * @param createBy the value for goods.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_by
     *
     * @return the value of goods.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_by
     *
     * @param updateBy the value for goods.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Goods{" +
                "id=" + id +
                ", startName='" + startName + '\'' +
                ", type=" + type +
                ", searchTimes=" + searchTimes +
                ", keyWord='" + keyWord + '\'' +
                ", haveBrushSingle=" + haveBrushSingle +
                ", evaluationTimes=" + evaluationTimes +
                ", havePictrueEvaluationTimes=" + havePictrueEvaluationTimes +
                ", salesCount=" + salesCount +
                ", brushSingleTimes=" + brushSingleTimes +
                ", brushSingleCost=" + brushSingleCost +
                ", detailsOptimization=" + detailsOptimization +
                ", remark='" + remark + '\'' +
                ", analyze='" + analyze + '\'' +
                ", createBy='" + createBy + '\'' +
                ", updateBy='" + updateBy + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}