package com.yan.shop.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.start_name
     *
     * @mbggenerated
     */
    private String startName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cost_price
     *
     * @mbggenerated
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sale_price
     *
     * @mbggenerated
     */
    private Double salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.give_good
     *
     * @mbggenerated
     */
    private Integer giveGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.have_picture
     *
     * @mbggenerated
     */
    private Integer havePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Double returnCash;

    public Double getReturnCash() {
        return returnCash;
    }

    public void setReturnCash(Double returnCash) {
        this.returnCash = returnCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.start_name
     *
     * @return the value of orders.start_name
     *
     * @mbggenerated
     */
    public String getStartName() {
        return startName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.start_name
     *
     * @param startName the value for orders.start_name
     *
     * @mbggenerated
     */
    public void setStartName(String startName) {
        this.startName = startName == null ? null : startName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.type
     *
     * @return the value of orders.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.type
     *
     * @param type the value for orders.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cost_price
     *
     * @return the value of orders.cost_price
     *
     * @mbggenerated
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cost_price
     *
     * @param costPrice the value for orders.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sale_price
     *
     * @return the value of orders.sale_price
     *
     * @mbggenerated
     */
    public Double getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sale_price
     *
     * @param salePrice the value for orders.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.give_good
     *
     * @return the value of orders.give_good
     *
     * @mbggenerated
     */
    public Integer getGiveGood() {
        return giveGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.give_good
     *
     * @param giveGood the value for orders.give_good
     *
     * @mbggenerated
     */
    public void setGiveGood(Integer giveGood) {
        this.giveGood = giveGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.have_picture
     *
     * @return the value of orders.have_picture
     *
     * @mbggenerated
     */
    public Integer getHavePicture() {
        return havePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.have_picture
     *
     * @param havePicture the value for orders.have_picture
     *
     * @mbggenerated
     */
    public void setHavePicture(Integer havePicture) {
        this.havePicture = havePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.phone
     *
     * @return the value of orders.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.phone
     *
     * @param phone the value for orders.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.remark
     *
     * @return the value of orders.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.remark
     *
     * @param remark the value for orders.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_by
     *
     * @return the value of orders.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_by
     *
     * @param createBy the value for orders.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_by
     *
     * @return the value of orders.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_by
     *
     * @param updateBy the value for orders.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_time
     *
     * @return the value of orders.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_time
     *
     * @param updateTime the value for orders.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}