server:
  port: 8080
  tomcat:
    max-connections: 200
    max-threads: 500
    uri-encoding: UTF-8
    max-http-post-size: 0
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      directory: ${LOG_PATH:logs}
      pattern: common
      rotate: true


spring:
  application:
      name: shop
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: UTF-8
#      content-type: text/html

mybatis:
    mapper-locations: classpath:mapper/*.xml

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/


